dependencies:
  - python=3.10.12
  - ipykernel
  - geopandas=0.13.2
  - kneed=0.8.5
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=1.5.3
  - conda==23.11.0
  - seaborn=0.12.2
  - shapely==2.0.2
  - scikit-learn=1.2.2
  - openpyxl
  - jupyterlab
  - esda==2.5.1
  - rasterio==1.3.9
  - scipy==1.11.4
  - yellowbrick==1.5
